[APG-1084] Add array_superstructure_srvs to bridged messages
locusrobotics/ros1_bridge pull request #21
Opened 2024-11-25 19:36 UTC by bmagyar

Builds on top of #20

2024-11-25 19:49 UTC, carlos-m159 commented on package.xml
> +  <build_depend>array_superstructure_srvs</build_depend>
This might require listing `array_superstructure_msgs` here as well?

2024-11-25 19:58 UTC, svwilliams commented on package.xml
> +  <build_depend>array_superstructure_srvs</build_depend>
I was just about to ask if there was a ROS1 version of the `array_superstructure_srvs` included in the build. I'm guessing "no".

I know we have a fancy "automatically convert ROS1 messages to ROS2" package here: https://github.com/locusrobotics/locus_ros2_messages

I'm not sure if going the opposite direction is supported.

2024-11-25 22:45 UTC, carlos-m159 commented on package.xml
> +  <build_depend>array_superstructure_srvs</build_depend>
Ah, right... I assumed it was a ROS1 pkg. It is going to be a problem then

2024-11-26 10:05 UTC, bmagyar commented on package.xml
> +  <build_depend>array_superstructure_srvs</build_depend>
The ROS1 versions also exist, located here: https://github.com/locusrobotics/locus_vector/tree/devel/vector_common

2024-11-26 13:43 UTC, svwilliams requested changes

2024-11-26 13:43 UTC, svwilliams commented on package.xml
> +  <build_depend>array_superstructure_srvs</build_depend>
The ROS1 Bridge message dependency system is not recursive. You will need to manually add all dependencies of `array_superstructure_srvs` to this list as well. At a minimum, you need `array_superstructure_msgs` in this list. But that is as far as I looked. There may be others.

2024-11-26 15:23 UTC, carlos-m159 approved these changes

2024-11-26 15:43 UTC, bmagyar commented on package.xml
> +  <build_depend>array_superstructure_srvs</build_depend>
Done!

2024-11-26 15:56 UTC, svwilliams approved these changes
Build server looks happy. Ship it.

2024-11-26 16:08 UTC, bmagyar commented
Thanks for the tips guys!

2024-11-26 16:08 UTC, merged